enyo.depends(
    "cookie.js",
    "deviceProfile.js",
    "feeds.js",
    "filePicker.js",
    "IPKGService.js",
    "packageModel.js",
    "packagesModel.js",
    "palmProfile.js",
    "typeConditions.js"
);
